### PR TITLE
Created util for linksInNewTab that tests for hrefs starting with https?://

### PR DESCRIPTION
**Pull request by jozanza**
This PR depends on https://github.com/egoist/marked3/pull/8 getting merged. We'll also want to bump the version number in `package.json` once that happens.

### CODE REVIEW

**Comment by egoist** [comment]
Can you update the lockfile as well? basically run `yarn add marked3` should do.

**Comment by jozanza** [comment]
Sure give me like 5 mins

**Comment by jozanza** [comment]
Okay updated 👍

**Comment by egoist** [comment]
Released v0.0.25

**Comment by jozanza** [comment]
Right on :)

**Pull request merged**
